### ISSUE TITLE
Patches

### ISSUE THREAD

**Issue by jonasstein** [mimecorg/fraqtive#5]
Hi, we have 2 patches at Gentoo. Do you wan to merge these?
https://gitweb.gentoo.org/repo/gentoo.git/tree/x11-misc/fraqtive/files

**Comment by AxeMax** [comment]
Hi @jonasstein , I just stumbled upon this cool software and pondered working on it a bit. Your patches work great for me (Kubuntu 22.04) and I turned them into a PR. Let's hope @mimecorg merges it.

**Comment by AxeMax** [comment]
Hey @jonasstein, @mimecorg merged the PR, can we close this issue?

**Comment by jonasstein** [comment]
@AxeMax yes. Thank you. It would be great, if you could tag a new release including the patches.

**Comment by AxeMax** [comment]
Good idea @jonasstein , but I don't think I have permissions to do this on this repository. Correct me if I'm wrong, but I think @mimecorg would have to do it.

**Comment by mimecorg** [comment]
@AxeMax I created a new release.

**Comment by AxeMax** [comment]
Thank you @mimecorg

**Comment by jonasstein** [comment]
Thanks all

**Comment by jonasstein** [comment]
@mimecorg there is a typo in the release version 
https://github.com/mimecorg/fraqtive/releases/tag/v0.4.8.1 vs. 0.8.4.1

**Comment by mimecorg** [comment]
Thanks @jonasstein, I haven't noticed that :).

**Comment by AxeMax** [comment]
@jonasstein can we close this now?

**Comment by jonasstein** [comment]
sure. And thanks again.
